### ISSUE TITLE
Default value for `leading` option?

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [react-cmpt/use-throttle#9]
In the readme, it doesn't say what the default option for `leading` is. I think it's `false`. Should someone add the default value to the docs?

**Comment by wangcch** [comment]
Hi Rajas @ChocolateLoverRaj, Thank you for your feedback.
You are right. The default value of `leading` is `false`. It has been updated in the new doc https://github.com/react-cmpt/use-throttle/commit/3c73587f401acc76866dc90d658d6dd15539f015.
Thanks.
